#baseURL = "https://andymcdgeo.github.io/"
baseURL = "https://www.andymcdonald.scot/"
languageCode = "en-uk"
title = "Andy McDonald"
theme = "hugo-tranquilpeak-theme"
summaryLength = 40
publishDir = "docs"
pygmentsUseClasses=true

googleAnalytics = "your-google-analytics-id"
enableRobotsTXT = true
canonifyURLs = true

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Blog"
  weight = 30
  identifier = "blog"
  url = "/blog/"

[[menu.main]]
  name = "Publications"
  weight = 30
  identifier = "publications"
  url = "/publications/"

[[menu.main]]
  name = "Projects"
  weight = 30
  identifier = "projects"
  url = "https://www.andymcdonald.scot/#projects"


[params]
  github = "andymcdgeo"
  name = "Andy McDonald"
  description = "Petrophysicist | Geoscientist | Data Scientist"
  email = "anthony.russel42@example.com"
  phone = "+234 23 9873237"
  
  year = 2021
  avatar = "images/andy.png"
  avatarclass = "circle"
  background = ""
  banner = "images/header_img.jpg"
  favicon = "images/favicon-16x16.png"
  DateForm = "January 2, 2006"
  showSubheader = true
  showServices = true
  showRecentWorks = true
  showDownload = true
  showClients = true
  

  project1_img = "images/project_las_explorer.png"
  project2_img = "images/project_python_petrophysics.png"
  project3_img = "images/project_spwla_workshop.png"

  footerEnableContact = false
  footerEnableFollowme = true
  footerEnableTextWidget = false
  footerEnableFormWidget = false

[params.disqus]
    site = ""

[params.sharethis]
    property = "123456789012345678901234"
    custom = true


[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/andymcdonaldgeo/"
  icon = "fab fa-linkedin"
  footer = true
[[params.social]]
  name = "researchgate"
  url = "https://www.researchgate.net/profile/Andrew-Mcdonald-15"
  icon = "fab fa-researchgate"
  footer = false
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/geoandymcd"
  icon = "fab fa-twitter-square"
  footer = true
  sharethis = true
  network = "twitter"
[[params.social]]
	title = "github"
	url = "https://github.com/andymcdgeo"
    icon = "fab fa-github-square"
    footer = true
    sharethis = true
    network = ""
[[params.social]]
	title = "medium"
	url = "https://andymcdonaldgeo.medium.com"
  icon = "fab fa-medium"
  footer = true
  sharethis = false
  network = "medium"
